language: r
r: 3.5.2
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install: [
        "sudo add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ xenial main\" -y",
        "sudo apt-get update -q",
        "echo 'Installing R package dependencies'",
        "sudo apt-get install libnlopt-dev",
        "sudo apt-get install r-cran-rcppeigen",
        "sudo apt-get install r-cran-plogr"
      ]
      install: Rscript Tools/requiredPackages.R JASP-Engine/JASP/R true true
      script:
        - cd JASP-Tests/R/tests/
        - R < testthat.R --no-save

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - VDIFFR_RUN_TESTS=true
