language: r
r: "3.4.3"
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install: [
        "sudo add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ xenial main\" -y",
        "sudo apt-get update -q",
        "echo 'Installing R package dependencies'",
        "sudo apt-get install libnlopt-dev",
        "sudo apt-get install r-cran-rcppeigen",
        "sudo apt-get install r-cran-plogr"
      ]
      install: Rscript -e 'install.packages("testthat"); install.packages("JASP-R-Interface/jaspResults/", repos=NULL, type="source")'
      script:
        - Rscript Tools/requiredPackages.R JASP-Engine/JASP/R true
        - cd JASP-Tests/R/tests/
        - R < testthat.R --no-save
